### ISSUE TITLE
Extracting configuration settings into external file

### ISSUE THREAD

**Issue by andrius-ordojan** [Praqma/job-dsl-collection#1]
I extracted all configuration into a separate dot properties file [here](https://github.com/Praqma/job-dsl-collection/blob/master/web-pipeline-dsl/config.properties) It can be injected using envinject plugin and read in the groovy script. Original plan was to use a YAML file, but from what I understand it would be really troublesome to add a yaml parser dependency.

I put the code for reading the variables in a separate file [here](https://github.com/Praqma/job-dsl-collection/blob/master/web-pipeline-dsl/read.groovy). 

Because of my lack of knowledge of the inner workings of the script I held of on integration.

**Comment by MadsNielsen** [comment]
Added a webconfig.groovy file with dot notation and closures for ConfigSlurper() support
```
"www.praqma.com" {
	github = "https://github.com/Praqma/praqma.com.git"
	integrationbranch = "gh-pages"
}

"www.josra.org" {
	github = "https://github.com/josra/josra.github.io.git"
	integrationbranch = "master"  
}

"www.code-conf.com" {
	github = "https://github.com/Praqma/code-conf.com.git"
	integrationbranch = "gh-pages"
}

"code-maturity.praqma.com" {
	github = "https://github.com/Praqma/code-maturity.git"
	integrationbranch = "gh-pages"
}
```

**Comment by MadsNielsen** [comment]
@lakruzz How does this look to you?
