### ISSUE TITLE
Linkchecker reports false negative

### ISSUE THREAD

**Issue by lakruzz** [Praqma/job-dsl-collection#15]
Have a look at this hob here:

http://code.praqma.net/ci/view/Website_Pipelines/view/Website_www.praqma.com/job/Web_www.praqma.com-linkcheck/7/warnings5Result/

I reports errors - but they are not really errors.

Referring to:
http://www.praqma.com/stories/linkckecker-jekyll-flavor/
http://www.praqma.com/stories/linkchecker-dockerized/

Problem is the regexp here http://code.praqma.net/ci/configure (Search for Compiler Warnings section) is wrong.

...fix (https://regex101.com/ is your friend)

**Comment by martinmosegaard** [comment]
The Jenkins configuration is set up to take as input a LinkChecker CSV report. If we look at the CSV file from build 7 above, http://code.praqma.net/ci/view/Website_Pipelines/view/Website_www.praqma.com/job/Web_www.praqma.com-linkcheck/7/

it appears to contain two types of results:
- result = `200 OK` and valid = True. Should not be a warning
- result = empty string and valid = True, for a `tel` URL. Should also not be a warning

**Comment by martinmosegaard** [comment]
I suppose one of these fixes might be applied:
- do not add these valid lines to the csv file
- do not return a `new Warning` in the mapping script

Depending on which is possible

**Comment by martinmosegaard** [comment]
The second issue, `tel:` URL warnings, is fixed in https://github.com/Praqma/job-dsl-collection/commit/de6dabe15d0f1436336f7dba6c3e3bcd1258327e#diff-b63d7c657087f0d36e2211f8e5e34256

**Comment by martinmosegaard** [comment]
I still don't understand why we see the first warnings reporting `200 OK`.

**Comment by anetacamo** [comment]
@martinmosegaard Hi Martin! Can I close this - or is it still in process? :)

**Comment by bicschneider** [comment]
not an issue anymore due to Praqma/praqma.com#1410

**Comment by bicschneider** [comment]
@martinmosegaard The reason is the warning of a `space` in the link .. 
```tel:: (ignored) Leading or trailing whitespace in URL `tel: '. - "Tel URL ignored. The URL is outside of the domain filter, checked only syntax."```
https://jenkins.praqma.cloud/view/Website_Pipelines/view/www.praqma.com/job/Web_www.praqma.com-linkcheck/247/warnings2Result/package.1059344965/
