### ISSUE TITLE
Resource checker fails BIG time - but reports no error

### ISSUE THREAD

**Issue by lakruzz** [Praqma/job-dsl-collection#16]
http://code.praqma.net/ci/view/Website_Pipelines/view/Website_www.praqma.com/job/Web_www.praqma.com-resource-analysis/7/console

Scrutinize this log - A LOT of things go wrong - this should be reported.

I suggest forcing the script to output something that's easy to parse and then use the Warning plugin to do the analysis

**Comment by lakruzz** [comment]
This is very much related to Praqma/praqma.com#832

**Comment by kryptag** [comment]
Both duplicates and Unused files will now make the build fail and send a message to the culprit.

**Comment by MadsNielsen** [comment]
Now fails properly. I'm getting emails for failed builds
